In [1]:
import pandas as pd
data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

In [2]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
data.shape

(1599, 12)

In [4]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(data)

In [5]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
375,11.5,0.54,0.71,4.40,0.124,6.0,15.0,0.99840,3.01,0.83,11.8,7
999,6.4,0.69,0.00,1.65,0.055,7.0,12.0,0.99162,3.47,0.53,12.9,6
311,7.9,0.53,0.24,2.00,0.072,15.0,105.0,0.99600,3.27,0.54,9.4,6
60,8.8,0.40,0.40,2.20,0.079,19.0,52.0,0.99800,3.44,0.64,9.2,5
685,8.1,0.78,0.23,2.60,0.059,5.0,15.0,0.99700,3.37,0.56,11.3,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1198,7.7,0.26,0.26,2.00,0.052,19.0,77.0,0.99510,3.15,0.79,10.9,6
969,6.7,0.56,0.09,2.90,0.079,7.0,22.0,0.99669,3.46,0.61,10.2,5
131,5.6,0.50,0.09,2.30,0.049,17.0,99.0,0.99370,3.63,0.63,13.0,5
1488,5.6,0.54,0.04,1.70,0.049,5.0,13.0,0.99420,3.72,0.58,11.4,5
789,8.6,0.63,0.17,2.90,0.099,21.0,119.0,0.99800,3.09,0.52,9.3,5

In [6]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
778,8.3,0.43,0.30,3.4,0.079,7.0,34.0,0.99788,3.36,0.61,10.5,5
1245,7.4,0.55,0.19,1.8,0.082,15.0,34.0,0.99655,3.49,0.68,10.5,5
1436,10.0,0.38,0.38,1.6,0.169,27.0,90.0,0.99914,3.15,0.65,8.5,5
1080,10.3,0.27,0.56,1.4,0.047,3.0,8.0,0.99471,3.16,0.51,11.8,6
836,6.7,0.28,0.28,2.4,0.012,36.0,100.0,0.99064,3.26,0.39,11.7,7
...,...,...,...,...,...,...,...,...,...,...,...,...
1429,7.9,0.18,0.40,2.2,0.049,38.0,67.0,0.99600,3.33,0.93,11.3,5
88,9.3,0.39,0.44,2.1,0.107,34.0,125.0,0.99780,3.14,1.22,9.5,5
355,6.7,0.75,0.01,2.4,0.078,17.0,32.0,0.99550,3.55,0.61,12.8,6
36,7.8,0.60,0.14,2.4,0.086,3.0,15.0,0.99750,3.42,0.60,10.8,6
354,6.1,0.21,0.40,1.4,0.066,40.5,165.0,0.99120,3.25,0.59,11.9,6

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import ElasticNet

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,accuracy_score,roc_auc_score
from sklearn.model_selection import  train_test_split

In [8]:
X_train=train.drop(["quality"],axis=1)
X_test=test.drop(["quality"],axis=1)
    
y_train=train[["quality"]]
y_test=test[["quality"]]

In [9]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)

C:\Users\72424\AppData\Local\Temp\ipykernel_8492\4040854503.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)

RandomForestClassifier()

In [10]:
X_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
778,8.3,0.43,0.30,3.4,0.079,7.0,34.0,0.99788,3.36,0.61,10.5
1245,7.4,0.55,0.19,1.8,0.082,15.0,34.0,0.99655,3.49,0.68,10.5
1436,10.0,0.38,0.38,1.6,0.169,27.0,90.0,0.99914,3.15,0.65,8.5
1080,10.3,0.27,0.56,1.4,0.047,3.0,8.0,0.99471,3.16,0.51,11.8
836,6.7,0.28,0.28,2.4,0.012,36.0,100.0,0.99064,3.26,0.39,11.7
...,...,...,...,...,...,...,...,...,...,...,...
1429,7.9,0.18,0.40,2.2,0.049,38.0,67.0,0.99600,3.33,0.93,11.3
88,9.3,0.39,0.44,2.1,0.107,34.0,125.0,0.99780,3.14,1.22,9.5
355,6.7,0.75,0.01,2.4,0.078,17.0,32.0,0.99550,3.55,0.61,12.8
36,7.8,0.60,0.14,2.4,0.086,3.0,15.0,0.99750,3.42,0.60,10.8
354,6.1,0.21,0.40,1.4,0.066,40.5,165.0,0.99120,3.25,0.59,11.9

In [11]:
pred_prob=rf.predict_proba(X_test)

In [12]:
roc_auc_score=roc_auc_score(y_test,pred_prob,multi_class='ovr')

In [13]:
roc_auc_score

0.8644654067200519